repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: python scripts/pre-commit/run_pylint.py
        language: python
        additional_dependencies:
          - pylint==3.3.7
        types:
          - python
        require_serial: true
        pass_filenames: true
      - id: lizard
        name: lizard
        entry: python scripts/pre-commit/run_lizard.py
        language: python
        additional_dependencies:
          - lizard
        files: \.(py|c|cc|cpp|h|hpp)$
        require_serial: true
        pass_filenames: true
      - id: markdownlint
        name: markdownlint-cli2
        entry: markdownlint-cli2 --config .markdownlint.jsonc
        language: node
        additional_dependencies:
          - markdownlint-cli2
        types:
          - markdown
        require_serial: true
        pass_filenames: true
