# Copyright 2026 Huawei Technologies Co., Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ============================================================================
"""Temporary FSDP2 integration for the tiny Trainer demos."""

import logging
from typing import Any

import torch.nn as nn

from hyper_parallel import fully_shard
from hyper_models.components.distributed.config import FSDP2Config

logger = logging.getLogger(__name__)


class FSDP2Manager:
    """FSDP2 wrapper manager used by the temporary Trainer demo.

    Canonical 2-arg constructor: (config, mesh_context).
    mesh_context carries device_mesh and device (C6 alignment).

    Note:
        The current implementation only recognizes the dummy GPT-2 and Llama
        models generated by the examples. It is a test stub rather than the
        general model-parallelization entry point.
    """

    def __init__(self, config: FSDP2Config, mesh_context: Any):
        self.config = config
        self.mesh_context = mesh_context
        self.device_mesh = getattr(mesh_context, "device_mesh", None)
        self.device = getattr(mesh_context, "device", "cuda")

    @staticmethod
    def _get_dummy_transformer_layers(model: nn.Module) -> nn.ModuleList:
        """Return the transformer layers of a supported dummy model.

        Args:
            model: Tiny GPT-2 or Llama model generated by the examples.

        Returns:
            Transformer layers to wrap as independent FSDP units.

        Raises:
            ValueError: If the model does not match a supported dummy model.
        """
        model_config = getattr(model, "config", None)
        model_type = getattr(model_config, "model_type", None)
        if model_type == "gpt2":
            transformer = getattr(model, "transformer", None)
            layers = getattr(transformer, "h", None)
        elif model_type == "llama":
            base_model = getattr(model, "model", None)
            layers = getattr(base_model, "layers", None)
        else:
            layers = None

        if not isinstance(layers, nn.ModuleList):
            raise ValueError(
                "FSDP2Manager.parallelize is currently a dummy-model stub and "
                "only supports the GPT-2 and Llama structures used by the "
                f"training examples, but got model_type={model_type!r}"
            )
        return layers

    def _parallelize_dummy_model(
        self,
        model: nn.Module,
        fsdp_mesh: Any,
    ) -> int:
        """Apply per-block and root FSDP to a supported tiny model.

        This follows the same wrapping order as Qwen3.5's ``_apply_fsdp``:
        snapshot the transformer layers, shard each layer as an independent
        FSDP unit, and finally shard the root model.

        Args:
            model: Tiny GPT-2 or Llama model built by a training example.
            fsdp_mesh: Data-parallel mesh used by every FSDP unit.

        Returns:
            Number of transformer blocks wrapped before the root model.
        """
        fsdp_kwargs = {
            "mesh": fsdp_mesh,
            "reshard_after_forward": self.config.reshard_after_forward,
        }
        transformer_layers = list(self._get_dummy_transformer_layers(model))
        for layer in transformer_layers:
            fully_shard(layer, **fsdp_kwargs)
        fully_shard(model, **fsdp_kwargs)
        return len(transformer_layers)

    def parallelize(
        self,
        model: nn.Module,
        tp_shard_plan: Any = None,
        tp_grad_info: dict | None = None,
    ) -> nn.Module:
        """Apply the training demos' temporary per-layer FSDP wrapping.

        This is intentionally a test-only stub for
        ``examples/training_demo``. It must be replaced by model-owned
        parallelization logic before other architectures use this manager.

        Args:
            model: Supported dummy model to shard in place.
            tp_shard_plan: Optional tensor-parallel sharding plan.
            tp_grad_info: Optional tensor-parallel gradient metadata.

        Returns:
            The model enhanced with the HyperParallel HSDPModule interface.

        Raises:
            ValueError: If no data-parallel mesh dimension is available, or TP
                was requested without producing a sharding plan.
        """
        if self.device_mesh is None:
            raise ValueError("FSDP2 requires a DeviceMesh, but MeshContext.device_mesh is None")

        tp_size = getattr(self.mesh_context, "tp_size", 1)
        if tp_size > 1 and (
            tp_shard_plan is None
            or not getattr(tp_shard_plan, "modules", None)
        ):
            raise ValueError(
                f"TP size {tp_size} was requested, but ShardingPlanner did not "
                "produce a non-empty plan before FSDP2 wrapping"
            )

        mesh_dim_names = self.device_mesh.mesh_dim_names
        if "dp_shard" not in mesh_dim_names:
            raise ValueError(
                "FSDP2 requires a 'dp_shard' DeviceMesh dimension, "
                f"but got {mesh_dim_names}"
            )
        fsdp_dim_names = tuple(
            dim_name
            for dim_name in ("dp_replicate", "dp_shard")
            if dim_name in mesh_dim_names
        )

        fsdp_mesh = (
            self.device_mesh[fsdp_dim_names]
            if len(fsdp_dim_names) > 1
            else self.device_mesh[fsdp_dim_names[0]]
        )
        num_layers = self._parallelize_dummy_model(
            model,
            fsdp_mesh,
        )
        logger.info(
            "Applied dummy-model FSDP stub over %d transformer blocks + root "
            "on dimensions %s (tp_grad_info=%s)",
            num_layers,
            fsdp_dim_names,
            tp_grad_info is not None,
        )
        return model


def _instantiate_fsdp2(*, config: Any, mesh_context: Any) -> FSDP2Manager | None:
    """Factory used by instantiate_infrastructure (01 §8.1 canonical signature)."""
    if config is None:
        return None
    if isinstance(config, FSDP2Config):
        return FSDP2Manager(config=config, mesh_context=mesh_context)
    logger.warning("Unexpected FSDP2 config type %s; returning None", type(config))
    return None
