# Copyright 2026 Huawei Technologies Co., Ltd
# Licensed under the Apache License, Version 2.0
# ============================================================================
"""Drift check: is the on-disk artifact still the bytes the frozen plan emits?

``check --all`` re-runs the emit offline and compares the
regenerated bytes against the bundle currently on disk.  A mismatch means the
bundle was hand-edited after generation (or the source/plan changed without a
signature bump) — the artifact is stale and must not be trusted.

Distinct from ``verify_signature`` (which compares the *projected spec* against
the stored meta) and ``verify_output_hashes`` (which compares file bytes
against the *hashes recorded in meta*): this check re-derives the expected
bytes from the meta itself, so it catches an edit that was also re-touched in
meta, or an emit-layer regression.
"""
from __future__ import annotations

import logging
import os
from typing import Any, Optional

from hyper_parallel.codegen.artifact import resolve_artifact_layout
from hyper_parallel.codegen.meta import load_codegen_meta

logger = logging.getLogger(__name__)


def verify_drift_intact(meta: Any, yaml_path: str) -> list[str]:
    """Regenerate the bundle from ``meta`` and compare with the on-disk files.

    Returns a list of drift descriptions (empty = intact).  Raises
    ``FileNotFoundError`` when meta or the bundle directory is missing.  When
    the original modeling source file can no longer be read (e.g. a remote-code
    cache was evicted), drift is *reported*, not silently skipped: the artifact
    cannot be re-validated against its origin.
    """
    layout = resolve_artifact_layout(yaml_path, model_name=_model_name(meta))
    if not os.path.isdir(layout.artifact_dir):
        raise FileNotFoundError(f"codegen drift: bundle missing at {layout.artifact_dir}")

    from hyper_parallel.codegen.emit import emit_bundle

    files = emit_bundle(layout, meta)

    drifts: list[str] = []
    for name, expected in files.items():
        path = os.path.join(layout.artifact_dir, name)
        if not os.path.isfile(path):
            drifts.append(f"{name}: missing on disk")
            continue
        with open(path, "r", encoding="utf-8", errors="replace") as handle:
            actual = handle.read()
        if actual != expected:
            drifts.append(f"{name}: bytes differ from re-emitted bundle")
    return drifts


def _model_name(meta: Any) -> Optional[str]:
    """The model name recorded in meta (the generated filename stems from it)."""
    return getattr(meta, "model_name", None)


__all__ = [
    "verify_drift_intact",
]
